branches: master
language: ruby
gemfile:
  - gemfiles/activerecord_3_0.gemfile
  - gemfiles/activerecord_3_1.gemfile
  - gemfiles/activerecord_3_2.gemfile
notifications:
  email:
    recipients:
      jmazzi@gmail.com
    on_success: never
    on_failure: always
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode
