language: ruby

rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.4

gemfile:
  - gemfiles/activerecord_4_2.gemfile
  - gemfiles/activerecord_5_0.gemfile
  - gemfiles/activerecord_5_1.gemfile
  - gemfiles/activerecord_5_2.gemfile

matrix:
  exclude:
  - rvm: 2.2.10
    gemfile: gemfiles/activerecord_5_0.gemfile
  - rvm: 2.2.10
    gemfile: gemfiles/activerecord_5_1.gemfile
  - rvm: 2.3.8
    gemfile: gemfiles/activerecord_5_0.gemfile
  - rvm: 2.3.8
    gemfile: gemfiles/activerecord_5_1.gemfile
  - rvm: 2.4.5
    gemfile: gemfiles/activerecord_5_0.gemfile
  - rvm: 2.4.5
    gemfile: gemfiles/activerecord_5_1.gemfile
  - rvm: 2.5.3
    gemfile: gemfiles/activerecord_5_0.gemfile
  - rvm: 2.5.3
    gemfile: gemfiles/activerecord_5_1.gemfile
  - rvm: 2.6.4
    gemfile: gemfiles/activerecord_5_0.gemfile
  - rvm: 2.6.4
    gemfile: gemfiles/activerecord_5_1.gemfile

services:
  - postgresql
  - mysql

before_script:
  - cp spec/default.database.yml spec/database.yml
  - psql -c 'CREATE DATABASE crypt_keeper_providers;' -U postgres
  - psql crypt_keeper_providers -c 'CREATE EXTENSION IF NOT EXISTS pgcrypto;' -U postgres
  - mysql -e 'CREATE DATABASE crypt_keeper_providers'

branches: master

notifications:
  email:
    recipients:
      jmazzi@gmail.com
    on_success: never
    on_failure: always
